version: '3.8'

services:
  redis:
    image: redis:7.0
    container_name: inponto-redis
    command: redis-server
    ports:
      - "6379:6379"
    networks:
      - celery-network

  celery_worker:
    build: .
    container_name: inponto-celery_worker
    command: celery -A inponto.tasks worker --loglevel=info
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - redis
    environment:
      - BROKER_URL=redis://inponto-redis:6379/0
      - BACKEND_URL=redis://inponto-redis:6379/0
    networks:
      - celery-network

  celery_beat:
    build: .
    container_name: inponto-celery_beat
    command: celery -A inponto.tasks beat --loglevel=info
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - redis
    environment:
      - BROKER_URL=redis://inponto-redis:6379/0
      - BACKEND_URL=redis://inponto-redis:6379/0
    networks:
      - celery-network

networks:
  celery-network:
    driver: bridge
