from decouple import config

USER = config('USER')
PASSWORD = config('PASSWORD')

TWILIO_ACCOUNT_SID = config('TWILIO_ACCOUNT_SID')
TWILIO_AUTH_TOKEN = config('TWILIO_AUTH_TOKEN')
TWILIO_PHONE_NUMBER = config('TWILIO_PHONE_NUMBER')
MY_NUMBER = config('MY_NUMBER')
CELERY_BROKER_URL= config('CELERY_BROKER_URL')